### ISSUE TITLE
Unable to create a transfer

### ISSUE THREAD

**Issue by RugnirViking** [Genhis/KRPC.MechJeb#18]
**Describe the bug**
Upon trying to create manouver nodes for a transfer, the server gets upset
```Traceback (most recent call last):
  File "b:\projects\KSP_Python_Controller\to_mun.py", line 21, in <module>
    hohmann.make_nodes()
  File "<string>", line 1, in <lambda>
  File "C:\Python39\lib\site-packages\krpc\client.py", line 163, in _invoke
    raise self._build_error(response.results[0].error)
krpc.types.MJServiceException: Object reference not set to an instance of an object
Server stack trace:
  at KRPC.MechJeb.Maneuver.Operation.MakeNodes () [0x000fb] in <f0ccb68cc19a43d1930dc76961343ebd>:0
  at (wrapper managed-to-native) System.Reflection.MonoMethod.InternalInvoke(System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <9577ac7a62ef43179789031239ba8798>:0
```
**Expected behavior**
It creates the manouver nodes.

**Code snippet to reproduce it (ideally in Python)**
```
import krpc

conn = krpc.connect(name="Targetmun")
sc = conn.space_center
mj = conn.mech_jeb


print("Starting Transfer")
planner = mj.maneuver_planner
hohmann = planner.operation_transfer
hohmann.make_nodes() # <- error occurs here
```

**Version details**
kRPC.MechJeb: 0.6.1
Kerbal Space Program: 1.12.3
kRPC: krpc-0.4.9
MechJeb2: 2.9.1.0

I couldn't find mechjeb 2.9.2.0 like the other issue mentioned. I was able to get the ascent guidance to work, so it's not a complete failure, just this part doesn't work. This occurs regardless of whether I had targeted the a celestial body or a vessel

I notice on startup I get "kRPC.Mechjeb may not work properly" and "MuMech.Operation_MakeNodesImpl() not found" which is probably a hint at the root cause here

**Comment by Genhis** [comment]
Hello, please install a MechJeb version newer than 2.9.1.0 (2.10 should be fine) and let me know if there are any issues.
